"""
Seed realistic NJ senior care facilities into Supabase.
Run: python scripts/seed_facilities.py

These are real NJ cities, counties, and realistic data points.
Facility names are illustrative — replace with scraped data later.
"""

import json
import re
from supabase_client import insert

def slugify(name: str, city: str) -> str:
    """Generate URL slug: facility-name-city-nj"""
    text = f"{name} {city} nj".lower()
    text = re.sub(r"[^a-z0-9\s-]", "", text)
    text = re.sub(r"[\s-]+", "-", text).strip("-")
    return text

FACILITIES = [
    {
        "name": "Sunrise Senior Living of Basking Ridge",
        "city": "Basking Ridge",
        "county": "Somerset",
        "address": "177 Madisonville Rd",
        "zip": "07920",
        "care_types": ["Assisted Living", "Memory Care"],
        "price_min": 6500,
        "price_max": 9500,
        "beds": 80,
        "citation_count": 0,
        "last_inspection": "2025-09-15",
        "inspection_summary": "No citations found during last inspection.",
        "accepts_medicaid": False,
        "accepts_medicare": False,
        "accepts_private": True,
        "languages": ["English", "Spanish"],
        "description": "A premier assisted living and memory care community in the heart of Somerset County, offering personalized care plans, chef-prepared meals, and engaging daily activities.",
        "amenities": ["Private rooms", "Garden", "Beauty salon", "Library", "Fitness center", "Transportation"],
        "phone": "(908) 555-0101",
        "website": "https://example.com/sunrise-basking-ridge",
        "lat": 40.7068,
        "lng": -74.5421,
    },
    {
        "name": "Atria Park of Glen Ellyn",
        "city": "Morristown",
        "county": "Morris",
        "address": "280 Madison Ave",
        "zip": "07960",
        "care_types": ["Assisted Living", "Independent Living"],
        "price_min": 5800,
        "price_max": 8200,
        "beds": 120,
        "citation_count": 1,
        "last_inspection": "2025-07-22",
        "inspection_summary": "One minor citation for documentation of medication administration times.",
        "accepts_medicaid": False,
        "accepts_medicare": False,
        "accepts_private": True,
        "languages": ["English"],
        "description": "Located in historic Morristown, this community offers a blend of independence and support with spacious apartments, fine dining, and a full calendar of social events.",
        "amenities": ["Pool", "Restaurant-style dining", "Concierge", "Garden", "Game room"],
        "phone": "(973) 555-0202",
        "website": "https://example.com/atria-morristown",
        "lat": 40.7968,
        "lng": -74.4815,
    },
    {
        "name": "Brighton Gardens of Edison",
        "city": "Edison",
        "county": "Middlesex",
        "address": "1 Lincoln Hwy",
        "zip": "08817",
        "care_types": ["Assisted Living", "Memory Care"],
        "price_min": 5200,
        "price_max": 7800,
        "beds": 96,
        "citation_count": 2,
        "last_inspection": "2025-11-03",
        "inspection_summary": "Two citations: incomplete resident assessment documentation and delayed maintenance request response.",
        "accepts_medicaid": True,
        "accepts_medicare": False,
        "accepts_private": True,
        "languages": ["English", "Hindi", "Gujarati"],
        "description": "A welcoming assisted living community in Edison serving the diverse Middlesex County population with culturally sensitive care and multilingual staff.",
        "amenities": ["Private rooms", "Garden", "Activity room", "Beauty salon", "Chapel"],
        "phone": "(732) 555-0303",
        "website": "https://example.com/brighton-edison",
        "lat": 40.5187,
        "lng": -74.4121,
    },
    {
        "name": "CareOne at Livingston",
        "city": "Livingston",
        "county": "Essex",
        "address": "68 Passaic Ave",
        "zip": "07039",
        "care_types": ["Nursing Home", "Memory Care"],
        "price_min": 8500,
        "price_max": 12000,
        "beds": 180,
        "citation_count": 3,
        "last_inspection": "2025-06-10",
        "inspection_summary": "Three citations: staffing ratio below requirement during evening shift, incomplete fall risk assessments, and medication storage temperature log gaps.",
        "accepts_medicaid": True,
        "accepts_medicare": True,
        "accepts_private": True,
        "languages": ["English", "Spanish", "Portuguese"],
        "description": "A full-service skilled nursing facility providing 24/7 medical care, rehabilitation services, and specialized memory care programming in Essex County.",
        "amenities": ["Rehabilitation gym", "Private rooms", "Outdoor courtyard", "Activity room", "Beauty salon"],
        "phone": "(973) 555-0404",
        "website": "https://example.com/careone-livingston",
        "lat": 40.7901,
        "lng": -74.3290,
    },
    {
        "name": "The Chelsea at Bridgewater",
        "city": "Bridgewater",
        "county": "Somerset",
        "address": "1000 Route 22 West",
        "zip": "08807",
        "care_types": ["Assisted Living"],
        "price_min": 5500,
        "price_max": 7000,
        "beds": 64,
        "citation_count": 0,
        "last_inspection": "2025-10-28",
        "inspection_summary": "No citations found during last inspection.",
        "accepts_medicaid": False,
        "accepts_medicare": False,
        "accepts_private": True,
        "languages": ["English"],
        "description": "A boutique assisted living community offering personalized care in a warm, home-like setting. Known for small resident-to-staff ratios and individualized attention.",
        "amenities": ["Home-cooked meals", "Garden", "Library", "Arts studio", "Pet-friendly"],
        "phone": "(908) 555-0505",
        "website": "https://example.com/chelsea-bridgewater",
        "lat": 40.5934,
        "lng": -74.6302,
    },
    {
        "name": "Brandywine Living at Princeton",
        "city": "Princeton",
        "county": "Mercer",
        "address": "4349 Route 1 South",
        "zip": "08540",
        "care_types": ["Assisted Living", "Memory Care", "Independent Living"],
        "price_min": 7200,
        "price_max": 11000,
        "beds": 140,
        "citation_count": 0,
        "last_inspection": "2025-12-05",
        "inspection_summary": "No citations found during last inspection.",
        "accepts_medicaid": False,
        "accepts_medicare": False,
        "accepts_private": True,
        "languages": ["English", "Mandarin"],
        "description": "An upscale senior living community near Princeton University offering resort-style amenities, gourmet dining, and comprehensive care programs.",
        "amenities": ["Pool", "Spa", "Fine dining", "Theater", "Fitness center", "Garden", "Concierge"],
        "phone": "(609) 555-0606",
        "website": "https://example.com/brandywine-princeton",
        "lat": 40.3487,
        "lng": -74.6593,
        "is_featured": True,
        "featured_since": "2025-01-15",
    },
    {
        "name": "Hackensack Meridian Nursing & Rehabilitation",
        "city": "Hackensack",
        "county": "Bergen",
        "address": "385 Prospect Ave",
        "zip": "07601",
        "care_types": ["Nursing Home"],
        "price_min": 9000,
        "price_max": 14000,
        "beds": 240,
        "citation_count": 4,
        "last_inspection": "2025-08-18",
        "inspection_summary": "Four citations: inadequate infection control procedures, missing resident care plan updates, staffing below required levels on two shifts, and delayed response to call bells.",
        "accepts_medicaid": True,
        "accepts_medicare": True,
        "accepts_private": True,
        "languages": ["English", "Spanish", "Korean", "Tagalog"],
        "description": "A large skilled nursing facility affiliated with the Hackensack Meridian Health network, offering rehabilitation, long-term care, and specialized medical services.",
        "amenities": ["Rehabilitation center", "Private rooms", "Outdoor area", "Activity room", "Chapel"],
        "phone": "(201) 555-0707",
        "website": "https://example.com/hackensack-meridian-nursing",
        "lat": 40.8859,
        "lng": -74.0435,
    },
    {
        "name": "Spring Hills Senior Communities",
        "city": "Cherry Hill",
        "county": "Camden",
        "address": "1450 Route 70 East",
        "zip": "08034",
        "care_types": ["Assisted Living", "Memory Care"],
        "price_min": 4800,
        "price_max": 7500,
        "beds": 88,
        "citation_count": 1,
        "last_inspection": "2025-05-20",
        "inspection_summary": "One citation for incomplete staff training documentation on dementia care protocols.",
        "accepts_medicaid": True,
        "accepts_medicare": False,
        "accepts_private": True,
        "languages": ["English", "Spanish"],
        "description": "A comfortable assisted living and memory care community in South Jersey, offering personalized care programs and a secure memory care neighborhood.",
        "amenities": ["Secured memory care wing", "Garden", "Activity room", "Beauty salon", "Transportation"],
        "phone": "(856) 555-0808",
        "website": "https://example.com/spring-hills-cherry-hill",
        "lat": 39.9340,
        "lng": -74.9955,
        "is_featured": True,
        "featured_since": "2025-03-01",
    },
    {
        "name": "Visiting Angels of Toms River",
        "city": "Toms River",
        "county": "Ocean",
        "address": "1861 Hooper Ave",
        "zip": "08753",
        "care_types": ["Home Care"],
        "price_min": 3000,
        "price_max": 5500,
        "beds": None,
        "citation_count": 0,
        "last_inspection": None,
        "inspection_summary": None,
        "accepts_medicaid": True,
        "accepts_medicare": True,
        "accepts_private": True,
        "languages": ["English", "Spanish"],
        "description": "Providing in-home care services to seniors in Ocean County including personal care, companionship, meal preparation, and medication reminders.",
        "amenities": ["Personal care", "Companionship", "Meal preparation", "Medication reminders", "Light housekeeping"],
        "phone": "(732) 555-0909",
        "website": "https://example.com/visiting-angels-toms-river",
        "lat": 39.9537,
        "lng": -74.1979,
    },
    {
        "name": "Harrogate Senior Living",
        "city": "Lakewood",
        "county": "Ocean",
        "address": "400 Locust St",
        "zip": "08701",
        "care_types": ["Independent Living", "Assisted Living", "Nursing Home"],
        "price_min": 4500,
        "price_max": 10000,
        "beds": 300,
        "citation_count": 2,
        "last_inspection": "2025-04-12",
        "inspection_summary": "Two citations: kitchen equipment maintenance issue and incomplete quarterly resident assessment for two residents.",
        "accepts_medicaid": True,
        "accepts_medicare": True,
        "accepts_private": True,
        "languages": ["English", "Yiddish", "Russian"],
        "description": "A continuing care retirement community (CCRC) in Lakewood offering independent living cottages, assisted living apartments, and skilled nursing — all on one campus.",
        "amenities": ["Cottages", "Pool", "Fitness center", "Restaurant", "Library", "Garden", "Transportation", "Chapel"],
        "phone": "(732) 555-1010",
        "website": "https://example.com/harrogate-lakewood",
        "lat": 40.0879,
        "lng": -74.2176,
    },
    {
        "name": "Arbor Terrace of Hamilton",
        "city": "Hamilton",
        "county": "Mercer",
        "address": "3371 Route 33",
        "zip": "08619",
        "care_types": ["Assisted Living", "Memory Care"],
        "price_min": 5000,
        "price_max": 7200,
        "beds": 72,
        "citation_count": 0,
        "last_inspection": "2025-11-20",
        "inspection_summary": "No citations found during last inspection.",
        "accepts_medicaid": False,
        "accepts_medicare": False,
        "accepts_private": True,
        "languages": ["English"],
        "description": "A purpose-built assisted living and memory care community with an innovative approach to dementia care, featuring small-house neighborhoods and person-centered programming.",
        "amenities": ["Memory care neighborhoods", "Garden", "Activity studio", "Salon", "Family gathering room"],
        "phone": "(609) 555-1111",
        "website": "https://example.com/arbor-terrace-hamilton",
        "lat": 40.2263,
        "lng": -74.6756,
    },
    {
        "name": "Comfort Keepers of Clifton",
        "city": "Clifton",
        "county": "Passaic",
        "address": "1020 Broad St",
        "zip": "07013",
        "care_types": ["Home Care"],
        "price_min": 2800,
        "price_max": 4800,
        "beds": None,
        "citation_count": 0,
        "last_inspection": None,
        "inspection_summary": None,
        "accepts_medicaid": True,
        "accepts_medicare": True,
        "accepts_private": True,
        "languages": ["English", "Spanish", "Arabic"],
        "description": "In-home senior care services for the Passaic County area, including personal care, transportation, companionship, and specialized dementia care at home.",
        "amenities": ["Personal care", "Transportation", "Companionship", "Dementia care", "Respite care"],
        "phone": "(973) 555-1212",
        "website": "https://example.com/comfort-keepers-clifton",
        "lat": 40.8584,
        "lng": -74.1638,
    },
    {
        "name": "Winchester Gardens",
        "city": "Maplewood",
        "county": "Essex",
        "address": "333 Elmwood Ave",
        "zip": "07040",
        "care_types": ["Independent Living", "Assisted Living"],
        "price_min": 5800,
        "price_max": 8500,
        "beds": 150,
        "citation_count": 1,
        "last_inspection": "2025-10-05",
        "inspection_summary": "One citation: emergency lighting battery replacement needed in one hallway.",
        "accepts_medicaid": False,
        "accepts_medicare": False,
        "accepts_private": True,
        "languages": ["English"],
        "description": "A gracious retirement community set on beautifully landscaped grounds in Maplewood, offering independent and assisted living with a focus on active, engaged lifestyles.",
        "amenities": ["Garden", "Pool", "Fitness center", "Restaurant", "Art studio", "Library", "Putting green"],
        "phone": "(973) 555-1313",
        "website": "https://example.com/winchester-gardens",
        "lat": 40.7312,
        "lng": -74.2735,
        "is_featured": True,
        "featured_since": "2025-02-01",
    },
    {
        "name": "Complete Care at Vineland",
        "city": "Vineland",
        "county": "Cumberland",
        "address": "1502 E Chestnut Ave",
        "zip": "08360",
        "care_types": ["Nursing Home"],
        "price_min": 7500,
        "price_max": 11000,
        "beds": 200,
        "citation_count": 5,
        "last_inspection": "2025-09-28",
        "inspection_summary": "Five citations: inadequate wound care documentation, missed medication administrations, insufficient staffing on night shift, resident elopement risk assessment gaps, and food temperature compliance issues.",
        "accepts_medicaid": True,
        "accepts_medicare": True,
        "accepts_private": True,
        "languages": ["English", "Spanish"],
        "description": "A skilled nursing facility in Cumberland County providing long-term care, post-acute rehabilitation, and memory care services.",
        "amenities": ["Rehabilitation center", "Activity room", "Outdoor courtyard", "Chapel"],
        "phone": "(856) 555-1414",
        "website": "https://example.com/complete-care-vineland",
        "lat": 39.4863,
        "lng": -75.0260,
    },
    {
        "name": "Brightview Senior Living of Paramus",
        "city": "Paramus",
        "county": "Bergen",
        "address": "15 E Ridgewood Ave",
        "zip": "07652",
        "care_types": ["Assisted Living", "Independent Living", "Memory Care"],
        "price_min": 6800,
        "price_max": 10500,
        "beds": 160,
        "citation_count": 0,
        "last_inspection": "2025-12-01",
        "inspection_summary": "No citations found during last inspection.",
        "accepts_medicaid": False,
        "accepts_medicare": False,
        "accepts_private": True,
        "languages": ["English", "Korean"],
        "description": "A modern senior living community in Bergen County offering vibrant independent living, supportive assisted living, and compassionate memory care in one beautiful campus.",
        "amenities": ["Rooftop terrace", "Fitness center", "Theater", "Art studio", "Salon", "Fine dining", "Garden"],
        "phone": "(201) 555-1515",
        "website": "https://example.com/brightview-paramus",
        "lat": 40.9445,
        "lng": -74.0705,
    },
    {
        "name": "Right at Home of Jersey City",
        "city": "Jersey City",
        "county": "Hudson",
        "address": "100 Montgomery St",
        "zip": "07302",
        "care_types": ["Home Care"],
        "price_min": 3200,
        "price_max": 5000,
        "beds": None,
        "citation_count": 0,
        "last_inspection": None,
        "inspection_summary": None,
        "accepts_medicaid": True,
        "accepts_medicare": True,
        "accepts_private": True,
        "languages": ["English", "Spanish", "Tagalog", "Hindi"],
        "description": "In-home senior care in Hudson County, providing personal care, medication management, meal preparation, and companionship services to seniors aging in place.",
        "amenities": ["Personal care", "Medication management", "Meal preparation", "Companionship", "Transportation"],
        "phone": "(201) 555-1616",
        "website": "https://example.com/right-at-home-jc",
        "lat": 40.7178,
        "lng": -74.0431,
    },
    {
        "name": "The Bristal at Woodcliff Lake",
        "city": "Woodcliff Lake",
        "county": "Bergen",
        "address": "340 Chestnut Ridge Rd",
        "zip": "07677",
        "care_types": ["Assisted Living", "Memory Care"],
        "price_min": 7500,
        "price_max": 12000,
        "beds": 108,
        "citation_count": 0,
        "last_inspection": "2025-11-15",
        "inspection_summary": "No citations found during last inspection.",
        "accepts_medicaid": False,
        "accepts_medicare": False,
        "accepts_private": True,
        "languages": ["English"],
        "description": "A luxury assisted living and memory care residence in Bergen County with hotel-style amenities, gourmet cuisine, and a dedicated Alzheimer's care program.",
        "amenities": ["Concierge", "Fine dining", "Spa", "Theater", "Library", "Garden", "Fitness center", "Art studio"],
        "phone": "(201) 555-1717",
        "website": "https://example.com/bristal-woodcliff",
        "lat": 41.0234,
        "lng": -74.0579,
    },
    {
        "name": "HomeWell Care Services of Newark",
        "city": "Newark",
        "county": "Essex",
        "address": "50 Park Pl",
        "zip": "07102",
        "care_types": ["Home Care"],
        "price_min": 2500,
        "price_max": 4200,
        "beds": None,
        "citation_count": 0,
        "last_inspection": None,
        "inspection_summary": None,
        "accepts_medicaid": True,
        "accepts_medicare": True,
        "accepts_private": True,
        "languages": ["English", "Spanish", "Portuguese", "Haitian Creole"],
        "description": "Affordable in-home care services for Newark and Essex County seniors, including personal care, light housekeeping, errand assistance, and 24-hour live-in care.",
        "amenities": ["Personal care", "Live-in care", "Light housekeeping", "Errand assistance", "Companionship"],
        "phone": "(973) 555-1818",
        "website": "https://example.com/homewell-newark",
        "lat": 40.7357,
        "lng": -74.1724,
    },
    {
        "name": "Autumn Lake Healthcare at New Brunswick",
        "city": "New Brunswick",
        "county": "Middlesex",
        "address": "8 Old New Brunswick Rd",
        "zip": "08901",
        "care_types": ["Nursing Home", "Memory Care"],
        "price_min": 8000,
        "price_max": 13000,
        "beds": 160,
        "citation_count": 2,
        "last_inspection": "2025-07-30",
        "inspection_summary": "Two citations: resident personal hygiene assistance documentation gaps and minor medication labeling discrepancy.",
        "accepts_medicaid": True,
        "accepts_medicare": True,
        "accepts_private": True,
        "languages": ["English", "Spanish"],
        "description": "A comprehensive skilled nursing and memory care facility near Rutgers University, offering short-term rehabilitation and long-term residential care.",
        "amenities": ["Rehabilitation gym", "Private rooms", "Outdoor courtyard", "Activity room", "Salon"],
        "phone": "(732) 555-1919",
        "website": "https://example.com/autumn-lake-nb",
        "lat": 40.4862,
        "lng": -74.4518,
    },
    {
        "name": "Artis Senior Living of Princeton Junction",
        "city": "West Windsor",
        "county": "Mercer",
        "address": "674 Princeton Hightstown Rd",
        "zip": "08550",
        "care_types": ["Memory Care"],
        "price_min": 7000,
        "price_max": 9500,
        "beds": 66,
        "citation_count": 0,
        "last_inspection": "2025-10-18",
        "inspection_summary": "No citations found during last inspection.",
        "accepts_medicaid": False,
        "accepts_medicare": False,
        "accepts_private": True,
        "languages": ["English", "Mandarin", "Hindi"],
        "description": "A dedicated memory care community using a positive approach to Alzheimer's and dementia care. Small-house design with 24/7 specialized staff and therapeutic programming.",
        "amenities": ["Secured community", "Garden", "Activity studio", "Sensory room", "Family room", "Salon"],
        "phone": "(609) 555-2020",
        "website": "https://example.com/artis-princeton-junction",
        "lat": 40.2826,
        "lng": -74.6254,
    },
]


def main():
    # Add slugs and state
    rows = []
    for f in FACILITIES:
        row = {**f, "state": "NJ"}
        row["slug"] = slugify(f["name"], f["city"])
        if "is_featured" not in row:
            row["is_featured"] = False
        if "featured_since" not in row:
            row["featured_since"] = None
        rows.append(row)

    print(f"Seeding {len(rows)} facilities into Supabase...")

    # Insert in batches of 10
    for i in range(0, len(rows), 10):
        batch = rows[i:i+10]
        try:
            result = insert("facilities", batch, upsert=True)
            print(f"  Inserted batch {i//10 + 1}: {len(result)} rows")
        except Exception as e:
            print(f"  ERROR on batch {i//10 + 1}: {e}")

    print("Done!")


if __name__ == "__main__":
    main()
